import type { Metadata } from "next";
import localFont from "next/font/local";
//import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
//import BootstrapClient from "@/componets/bootstrap/BootstrapClient";
import TheNavBar from "@/componets/global/TheNavBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TheNavBar />
        {children}
        {/* <script src="./bootstrap/bootstrap.bundle.min.js"></script>
        <script src="./bootstrap/popper.min.js"></script>
        <script src="./bootstrap/bootstrap.min.js"></script> */}
      </body>
    </html>
  );
}
